[tool.poetry]
name = "mosdex-python"
version = "0.1.0"
description = "python project for testing Mosdex"
authors = ["Alan King <kingaj@us.ibm.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
